apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts: # tells skaffold about something inside the project it needs to maintain (hot reload in this case with pod/service update)
    - image: denley777/client # image tag
      context: client # directory
      sync:  # update will also work when adding new dependency - it will rebuild image and update it inside cluster
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: denley777/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: denley777/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: denley777/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: denley777/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: denley777/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false # disabling pushing to docker hub
manifests:
  rawYaml:
    - ./infra/k8s/*  # skaffold will watch for the changes inside this path and apply them
deploy:
  kubectl: {}